version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  transaction_manager_service:
    build:
      context: ./transaction_manager_service
    ports:
      - "5003:5003"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  transaction_service:
    build:
      context: ./transaction_service
    ports:
      - "5004:5004"
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: ["sh", "-c", "sleep 10 && python app.py"]  # Задержка для ожидания подключения к сервисам

  valute_converter_service:
    build:
      context: ./valute_converter_service
    ports:
      - "5002:5002"
